// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: src/proto/math.proto

#include <xrpc/proto/math.grpc.pb.h>
#include <xrpc/proto/math.pb.h>

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace xrpc {
namespace math {

static const char* MathService_method_names[] = {
  "/xrpc.math.MathService/CalculateMath",
};

std::unique_ptr< MathService::Stub> MathService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< MathService::Stub> stub(new MathService::Stub(channel, options));
  return stub;
}

MathService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_CalculateMath_(MathService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status MathService::Stub::CalculateMath(::grpc::ClientContext* context, const ::xrpc::math::MathRequest& request, ::xrpc::math::MathResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::xrpc::math::MathRequest, ::xrpc::math::MathResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_CalculateMath_, context, request, response);
}

void MathService::Stub::async::CalculateMath(::grpc::ClientContext* context, const ::xrpc::math::MathRequest* request, ::xrpc::math::MathResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::xrpc::math::MathRequest, ::xrpc::math::MathResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_CalculateMath_, context, request, response, std::move(f));
}

void MathService::Stub::async::CalculateMath(::grpc::ClientContext* context, const ::xrpc::math::MathRequest* request, ::xrpc::math::MathResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_CalculateMath_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::xrpc::math::MathResponse>* MathService::Stub::PrepareAsyncCalculateMathRaw(::grpc::ClientContext* context, const ::xrpc::math::MathRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::xrpc::math::MathResponse, ::xrpc::math::MathRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_CalculateMath_, context, request);
}

::grpc::ClientAsyncResponseReader< ::xrpc::math::MathResponse>* MathService::Stub::AsyncCalculateMathRaw(::grpc::ClientContext* context, const ::xrpc::math::MathRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncCalculateMathRaw(context, request, cq);
  result->StartCall();
  return result;
}

MathService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      MathService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< MathService::Service, ::xrpc::math::MathRequest, ::xrpc::math::MathResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](MathService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::xrpc::math::MathRequest* req,
             ::xrpc::math::MathResponse* resp) {
               return service->CalculateMath(ctx, req, resp);
             }, this)));
}

MathService::Service::~Service() {
}

::grpc::Status MathService::Service::CalculateMath(::grpc::ServerContext* context, const ::xrpc::math::MathRequest* request, ::xrpc::math::MathResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace xrpc
}  // namespace math

