// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: src/proto/math.proto
#ifndef GRPC_src_2fproto_2fmath_2eproto__INCLUDED
#define GRPC_src_2fproto_2fmath_2eproto__INCLUDED

#include "src/proto/math.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>

namespace xrpc {
namespace math {

class MathService final {
 public:
  static constexpr char const* service_full_name() {
    return "xrpc.math.MathService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status CalculateMath(::grpc::ClientContext* context, const ::xrpc::math::MathRequest& request, ::xrpc::math::MathResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::xrpc::math::MathResponse>> AsyncCalculateMath(::grpc::ClientContext* context, const ::xrpc::math::MathRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::xrpc::math::MathResponse>>(AsyncCalculateMathRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::xrpc::math::MathResponse>> PrepareAsyncCalculateMath(::grpc::ClientContext* context, const ::xrpc::math::MathRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::xrpc::math::MathResponse>>(PrepareAsyncCalculateMathRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void CalculateMath(::grpc::ClientContext* context, const ::xrpc::math::MathRequest* request, ::xrpc::math::MathResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void CalculateMath(::grpc::ClientContext* context, const ::xrpc::math::MathRequest* request, ::xrpc::math::MathResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::xrpc::math::MathResponse>* AsyncCalculateMathRaw(::grpc::ClientContext* context, const ::xrpc::math::MathRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::xrpc::math::MathResponse>* PrepareAsyncCalculateMathRaw(::grpc::ClientContext* context, const ::xrpc::math::MathRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status CalculateMath(::grpc::ClientContext* context, const ::xrpc::math::MathRequest& request, ::xrpc::math::MathResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::xrpc::math::MathResponse>> AsyncCalculateMath(::grpc::ClientContext* context, const ::xrpc::math::MathRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::xrpc::math::MathResponse>>(AsyncCalculateMathRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::xrpc::math::MathResponse>> PrepareAsyncCalculateMath(::grpc::ClientContext* context, const ::xrpc::math::MathRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::xrpc::math::MathResponse>>(PrepareAsyncCalculateMathRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void CalculateMath(::grpc::ClientContext* context, const ::xrpc::math::MathRequest* request, ::xrpc::math::MathResponse* response, std::function<void(::grpc::Status)>) override;
      void CalculateMath(::grpc::ClientContext* context, const ::xrpc::math::MathRequest* request, ::xrpc::math::MathResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::xrpc::math::MathResponse>* AsyncCalculateMathRaw(::grpc::ClientContext* context, const ::xrpc::math::MathRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::xrpc::math::MathResponse>* PrepareAsyncCalculateMathRaw(::grpc::ClientContext* context, const ::xrpc::math::MathRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_CalculateMath_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status CalculateMath(::grpc::ServerContext* context, const ::xrpc::math::MathRequest* request, ::xrpc::math::MathResponse* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_CalculateMath : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_CalculateMath() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_CalculateMath() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CalculateMath(::grpc::ServerContext* /*context*/, const ::xrpc::math::MathRequest* /*request*/, ::xrpc::math::MathResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestCalculateMath(::grpc::ServerContext* context, ::xrpc::math::MathRequest* request, ::grpc::ServerAsyncResponseWriter< ::xrpc::math::MathResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_CalculateMath<Service > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_CalculateMath : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_CalculateMath() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::xrpc::math::MathRequest, ::xrpc::math::MathResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::xrpc::math::MathRequest* request, ::xrpc::math::MathResponse* response) { return this->CalculateMath(context, request, response); }));}
    void SetMessageAllocatorFor_CalculateMath(
        ::grpc::MessageAllocator< ::xrpc::math::MathRequest, ::xrpc::math::MathResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::xrpc::math::MathRequest, ::xrpc::math::MathResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_CalculateMath() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CalculateMath(::grpc::ServerContext* /*context*/, const ::xrpc::math::MathRequest* /*request*/, ::xrpc::math::MathResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* CalculateMath(
      ::grpc::CallbackServerContext* /*context*/, const ::xrpc::math::MathRequest* /*request*/, ::xrpc::math::MathResponse* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_CalculateMath<Service > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_CalculateMath : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_CalculateMath() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_CalculateMath() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CalculateMath(::grpc::ServerContext* /*context*/, const ::xrpc::math::MathRequest* /*request*/, ::xrpc::math::MathResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_CalculateMath : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_CalculateMath() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_CalculateMath() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CalculateMath(::grpc::ServerContext* /*context*/, const ::xrpc::math::MathRequest* /*request*/, ::xrpc::math::MathResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestCalculateMath(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_CalculateMath : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_CalculateMath() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->CalculateMath(context, request, response); }));
    }
    ~WithRawCallbackMethod_CalculateMath() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status CalculateMath(::grpc::ServerContext* /*context*/, const ::xrpc::math::MathRequest* /*request*/, ::xrpc::math::MathResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* CalculateMath(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_CalculateMath : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_CalculateMath() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::xrpc::math::MathRequest, ::xrpc::math::MathResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::xrpc::math::MathRequest, ::xrpc::math::MathResponse>* streamer) {
                       return this->StreamedCalculateMath(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_CalculateMath() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status CalculateMath(::grpc::ServerContext* /*context*/, const ::xrpc::math::MathRequest* /*request*/, ::xrpc::math::MathResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedCalculateMath(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::xrpc::math::MathRequest,::xrpc::math::MathResponse>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_CalculateMath<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_CalculateMath<Service > StreamedService;
};

}  // namespace math
}  // namespace xrpc


#endif  // GRPC_src_2fproto_2fmath_2eproto__INCLUDED
